### ISSUE TITLE
Missing rsyslog configuration

### ISSUE THREAD

**Issue by svandragt** [Chassis/Cavalcade#28]
The readme mentions that the cavalcade log logfiles are located at /var/log/upstart/cavalcade.log but this is not the case as the rsyslog configuration isn't added to /etc/rsyslog.d

I expect to see the following configuration in `/etc/rsyslog.d/20-cavalcade.conf`:

     :msg,contains," cavalcade[" /var/log/upstart/cavalcade.log

1. What operating system do you use? macOS Mojave

2. What version of Vagrant are you running? 2.2.5

3. Are you using VirtualBox or VMWare and which version are you using? Virtualbox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```
extensions:
  - chassis/cavalcade
  [..]

synced_folders:
  logs/upstart: /var/log/upstart
  [..]
````
5. Do you have any Chassis other extensions installed? If so, what are they?
  - chassis/composer
  - chassis/mailhog
  - chassis/memcache
  - chassis/nodejs
  - chassis/sequelpro
  - chassis/xdebug
  - chassis/chassis_openssl

**Comment by svandragt** [comment]
I can confirm the above works, are you happy to receive a PR on this? If so I will try to learn the puppet syntax.

**Comment by BronsonQuick** [comment]
@svandragt Thanks so much for reporting this issue and letting us know the fix. I've done a PR and merge this into the plugin now. Thank you! 💖
