### ISSUE TITLE
pcntl_signal() has been disabled for security reasons

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Cavalcade#5]
Calvalcade uses [pcntl_signal](https://github.com/humanmade/Cavalcade/blob/master/class-command.php#L26) however this is disabled in the default Chassis PHP [configuration](https://github.com/Chassis/Chassis/blob/master/puppet/modules/chassis/templates/php.ini.erb#L317).

The extension should automatically configure this so we don't get the following warning message when we try and run `wp cavalcade run <id>`
```
PHP Warning:  pcntl_signal() has been disabled for security reasons in /vagrant/content/mu-plugins/vendor/cavalcade/class-command.php on line 26
```

**Comment by rmccue** [comment]
This is a flow-on effect from https://github.com/Chassis/Chassis/pull/374#pullrequestreview-38825173

**Comment by BronsonQuick** [comment]
Hah. I was just packing my bags and I thought I should cross post that issue. Thanks!

**Comment by BronsonQuick** [comment]
This issue can be fixed by using the [phpini](https://github.com/Chassis/phpini) extension.

**Comment by rmccue** [comment]
This is required for it to work, so we should fix it either in this extension or Chassis itself.

**Comment by BronsonQuick** [comment]
Fixed via: https://github.com/Chassis/Cavalcade/pull/8

**Comment by BronsonQuick** [comment]
As it turns out I only fixed this in php-fpm and not the cli
